name: 'Get previous stable releases'
description: 'A Github action for posting release notes to slack'
inputs:
  user:
    description: 'user'
    required: true
  repoName:
    description: 'repoName'
    required: true
  accessToken:
    description: 'accessToken'
    required: true
outputs:
  previousStableTag:
    description: 'previousStableTag'
  previousSecondStableTag:
    description: 'previousSecondStableTag'
  previousThirdStableTag:
    description: 'previousThirdStableTag'
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'at-sign'
  color: 'gray-dark'
