name: 'Get previous releases'
description: 'A Github action to get the previous releases'
inputs:
  user:
    description: 'user'
    required: true
  repoName:
    description: 'repoName'
    required: true
  accessToken:
    description: 'accessToken'
    required: true
  stable:
    description: 'Is stable release required? Boolean value'
    required: false
    default: 'true'
outputs:
  previousTag:
    description: 'previousTag'
  previousSecondTag:
    description: 'previousSecondTag'
  previousThirdTag:
    description: 'previousThirdTag'
runs:
  using: 'node16'
  main: 'dist/index.js'
branding:
  icon: 'at-sign'
  color: 'gray-dark'
